from awsglue.transforms import DropFields as DropFields, GlueTransform as GlueTransform

class ApplyMapping(GlueTransform):
    def __call__(self, frame, mappings, case_sensitive: bool = ..., transformation_ctx: str = ..., info: str = ..., stageThreshold: int = ..., totalThreshold: int = ...): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...
