from awsglue.transforms import GlueTransform as GlueTransform

class SelectFromCollection(GlueTransform):
    def __call__(self, dfc, key, transformation_ctx: str = ...): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...

class MapToCollection(GlueTransform):
    def __call__(self, dfc, callable, transformation_ctx: str = ...): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...

class FlatMap(GlueTransform):
    def __call__(self, dfc, BaseTransform, frame_name, transformation_ctx: str = ..., **base_kwargs): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...
