from awsglue.transforms import GlueTransform as GlueTransform

class Filter(GlueTransform):
    def __call__(self, frame, f, transformation_ctx: str = ..., info: str = ..., stageThreshold: int = ..., totalThreshold: int = ...): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...
