from awsglue.transforms import GlueTransform as GlueTransform

class ErrorsAsDynamicFrame(GlueTransform):
    def __call__(self, frame): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...
