from awsglue.transforms import GlueTransform as GlueTransform
from typing import Any

class ResolveChoice(GlueTransform):
    def __call__(self, frame, specs: Any | None = ..., choice: str = ..., database: Any | None = ..., table_name: Any | None = ..., transformation_ctx: str = ..., info: str = ..., stageThreshold: int = ..., totalThreshold: int = ..., catalog_id: Any | None = ...): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...
