class GlueTransform:
    @classmethod
    def apply(cls, *args, **kwargs): ...
    @classmethod
    def name(cls): ...
    @classmethod
    def describeArgs(cls) -> None: ...
    @classmethod
    def describeReturn(cls) -> None: ...
    @classmethod
    def describeTransform(cls) -> None: ...
    @classmethod
    def describeErrors(cls) -> None: ...
    @classmethod
    def describe(cls): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
