from awsglue.transforms import GlueTransform as GlueTransform

class Unbox(GlueTransform):
    def __call__(self, frame, path, format, transformation_ctx: str = ..., info: str = ..., stageThreshold: int = ..., totalThreshold: int = ..., **options): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...
