import requests
from .connector_activation_util import boto_client_error as boto_client_error
from typing import Any, Dict, List, Tuple, Union

LAYER_TAR_DIR: str
LAYER_GZ_DIR: str
MARKETPLACE: str
CUSTOM: str
HTTP_PROXY: str
HTTPS_PROXY: str
NO_PROXY: str
logger: Any

def add_stream_handler() -> None: ...
def run_commands(commands: List[str]) -> Tuple[bytes, bytes]: ...
def send_get_request(url: str, header: Dict[str, str]) -> requests.Response: ...
def parse_url(url: str) -> Tuple[str, str]: ...
def extract_ecr_region(ecr_root: str) -> Union[None, str]: ...
def extract_registry_id(ecr_root: str) -> str: ...
def get_ecr_authorization_token(ecr_root: str) -> str: ...
def parse_ecr_url(ecr_url: str) -> Tuple[str, str, str]: ...
def get_docker_manifest(ecr_url: str, header: Dict[str, str]) -> Dict[str, Any]: ...
def download_and_unpack_docker_layer(ecr_url: str, digest: str, dir_prefix: str, header: Dict[str, str]) -> None: ...
def parse_args(args: List[str]) -> List[str]: ...
def id_generator(size: int = ..., chars: str = ...) -> str: ...
def get_connection(region: str, endpoint: str, conn: str, proxy: str = ...) -> Union[Dict, None]: ...
def collect_files_by_suffix(input_dir: str, suffix: str) -> List[str]: ...
def download_custom_jars(conn: Dict[str, Any], dest_folder: str = ...): ...
def download_jars_per_connection(conn: str, region: str, endpoint: str, proxy: str = ...) -> List[str]: ...
def main() -> None: ...
