from typing import Any

class DataFrameReader:
    def __init__(self, glue_context) -> None: ...
    def from_catalog(self, database: Any | None = ..., table_name: Any | None = ..., redshift_tmp_dir: str = ..., transformation_ctx: str = ..., push_down_predicate: str = ..., additional_options=..., catalog_id: Any | None = ..., **kwargs): ...
    def from_options(self, connection_type, connection_options=..., format: Any | None = ..., format_options=..., transformation_ctx: str = ..., push_down_predicate: str = ..., **kwargs): ...
