from awsglue.dynamicframe import DynamicFrame as DynamicFrame, DynamicFrameCollection as DynamicFrameCollection
from awsglue.utils import callsite as callsite, makeOptions as makeOptions

class DataSink:
    def __init__(self, j_sink, sql_ctx) -> None: ...
    def setFormat(self, format, **options) -> None: ...
    def setAccumulableSize(self, size) -> None: ...
    def setCatalogInfo(self, catalogDatabase, catalogTableName, catalogId: str = ...) -> None: ...
    def writeFrame(self, dynamic_frame, info: str = ...): ...
    def write(self, dynamic_frame_or_dfc, info: str = ...): ...
