from awsglue.utils import callsite as callsite, makeOptions as makeOptions
from typing import Any

class StreamingDataSource:
    name: Any
    def __init__(self, j_source, sql_ctx, name) -> None: ...
    def setFormat(self, format, **options) -> None: ...
    def getFrame(self): ...
