import argparse
from awsglue.job import Job as Job

def makeOptions(sc, py_obj): ...
def callsite(): ...
def iteritems(d, **kwargs): ...
def iterkeys(d, **kwargs): ...
def itervalues(d, **kwargs): ...

class GlueArgumentError(Exception): ...

class GlueArgumentParser(argparse.ArgumentParser):
    def error(self, msg) -> None: ...

def getResolvedOptions(args, options): ...
