from awsglue import DynamicFrame

class ApplyMapping:
    @staticmethod
    def apply(frame: DynamicFrame, mappings: list[tuple[str, str, str, str]]) -> DynamicFrame: ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...
